bank:
  db:
    host: mysql
    port: 3306
    database: bank
    username: root
    password: 1234
  redis:
    host: redis
    port: 6379
    database: 1
  minio:
    endpoint: http://minio:9000
    documents-bucket-name: documents
    access-key: douzhan
    secret-key: minioadmin