
server:
  port: 8888 #https端口
  ssl:
    key-store: classpath:cumtbank.jks
    key-store-password: 123456              #压缩包解压里面会有
    key-store-type: JKS
    enabled: true
spring:
  application:
    name: bank
  profiles:
    active: pro
#  devtools:
#    restart:
#      enabled: true

  data:
    redis:
      host: ${bank.redis.host}
      port:  ${bank.redis.port}
      database:  ${bank.redis.database}
      connect-timeout: 3000ms
      jedis:
        pool:
          enabled: true
          max-active: 20
          max-idle: 8
          min-idle: 3
          max-wait: -1

  datasource: #mybatis配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${bank.db.host}:${bank.db.port}/${bank.db.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${bank.db.username}
    password: ${bank.db.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 20MB
      file-size-threshold: 512KB   # 当上传文件达到指定配置量的时候会将文件内容写入磁盘
      location: classpath            # 设置上传的临时目录
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai

mybatis-plus: # mp配置
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      update-strategy: not_null
      id_type: auto
    banner: off
  type-aliases-package: xyz.douzhan.bank.domain.po



logging: # 日志
  level:
    xyz.douzhan: info
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

management: # actuator配置
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - xyz.douzhan.bank.controller
  packages-to-scan:
    - xyz.douzhan.bank.controller
  show-actuator: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-home-custom: true
    home-custom-path: classpath:static/markdown/APIHome.md




